# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-19 13:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='资金账户类型定义', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='交易方向', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CapitalAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(help_text='资金账号', max_length=200)),
                ('account_pass', models.CharField(help_text='资金账号密码', max_length=200)),
                ('total_money', models.FloatField(default=0, help_text='账户总资金')),
                ('allocation_money', models.FloatField(default=0, help_text='可分配资金')),
                ('enable_money', models.FloatField(default=0, help_text='可用资金')),
                ('ssag', models.CharField(help_text='上证股东代码', max_length=200)),
                ('szag', models.CharField(help_text='深证股东代码', max_length=200)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('lastupdate_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='交易品种名字', max_length=200)),
                ('code', models.CharField(help_text='交易品种代码', max_length=50)),
                ('current_price', models.FloatField(default=0, help_text='交易品种当前价')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='交易品种状态', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='资金账户对应公司', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HoldCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hold_number', models.FloatField(default=0, help_text='持仓数量')),
                ('frozen_number', models.FloatField(default=0, help_text='冻结数量')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('lastupdate_time', models.DateTimeField(auto_now=True)),
                ('code', models.ForeignKey(help_text='持仓品种代码', on_delete=django.db.models.deletion.CASCADE, to='app.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(help_text='证券公司的委托单号', max_length=200)),
                ('price', models.FloatField(default=0, help_text='交易价格')),
                ('pretrade_money', models.FloatField(default=0, help_text='预交易资金')),
                ('pretrade_number', models.FloatField(default=0, help_text='预交易数量')),
                ('is_market_price', models.BooleanField(default=False, help_text='是否市场价成交')),
                ('already_trade_money', models.FloatField(default=0, help_text='实际已成交资金')),
                ('already_trade_number', models.FloatField(default=0, help_text='实际已成交数量')),
                ('waiting_trade_money', models.FloatField(default=0, help_text='等待成交金额')),
                ('waiting_trade_number', models.FloatField(default=0, help_text='等待成交数量')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='请求创建时间')),
                ('lastupdate_time', models.DateTimeField(auto_now=True, help_text='最后更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(help_text='交易状态', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StrategyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_money', models.FloatField(default=0, help_text='策略账户总资金')),
                ('enable_money', models.FloatField(default=0, help_text='策略账户可用资金')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('lastupdate_time', models.DateTimeField(auto_now=True, help_text='最后修改时间')),
                ('capitalaccount', models.ForeignKey(help_text='资金账户', on_delete=django.db.models.deletion.CASCADE, to='app.CapitalAccount')),
                ('holdlist', models.ManyToManyField(blank=True, help_text='策略账户总持仓', to='app.HoldCategory')),
                ('user', models.ForeignKey(help_text='策略账户，也就是系统账户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='strategy_account',
            field=models.ForeignKey(help_text='策略账户', on_delete=django.db.models.deletion.CASCADE, to='app.StrategyUser'),
        ),
        migrations.AddField(
            model_name='record',
            name='trade_action',
            field=models.ForeignKey(default=1, help_text='交易方向', on_delete=django.db.models.deletion.CASCADE, to='app.Action'),
        ),
        migrations.AddField(
            model_name='record',
            name='trade_category',
            field=models.ForeignKey(default=1, help_text='交易对象', on_delete=django.db.models.deletion.CASCADE, to='app.Category'),
        ),
        migrations.AddField(
            model_name='record',
            name='trade_status',
            field=models.ForeignKey(default=1, help_text='交易状态', on_delete=django.db.models.deletion.CASCADE, to='app.Status'),
        ),
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.ForeignKey(help_text='交易品种状态', on_delete=django.db.models.deletion.CASCADE, to='app.CategoryStatus'),
        ),
        migrations.AddField(
            model_name='capitalaccount',
            name='company',
            field=models.ForeignKey(default=1, help_text='证券公司或者期货公司', on_delete=django.db.models.deletion.CASCADE, to='app.Company'),
        ),
        migrations.AddField(
            model_name='capitalaccount',
            name='type',
            field=models.ForeignKey(default=1, help_text='账户类型，股票账户，期货账户，回测账户', on_delete=django.db.models.deletion.CASCADE, to='app.AccountType'),
        ),
    ]
