# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-12 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockticket',
            name='order_date',
            field=models.CharField(help_text='委托日期', max_length=200),
        ),
        migrations.AlterField(
            model_name='stockticket',
            name='order_time',
            field=models.CharField(help_text='委托时间', max_length=200),
        ),
    ]
