# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-19 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_capitalaccount_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounttype',
            old_name='value',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='capitalaccount',
            name='ssag',
            field=models.CharField(blank=True, help_text='上证股东代码', max_length=200),
        ),
        migrations.AlterField(
            model_name='capitalaccount',
            name='szag',
            field=models.CharField(blank=True, help_text='深证股东代码', max_length=200),
        ),
    ]
