# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-12 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180312_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockticket',
            name='cancel_mark',
            field=models.CharField(help_text='撤单标志', max_length=30),
        ),
    ]
