# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-19 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20171219_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitalaccount',
            name='initial_money',
            field=models.FloatField(default=0, help_text='账户初始资金'),
        ),
    ]
