# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-19 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180312_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='earnest_capital',
            field=models.FloatField(default=0, help_text='保证金'),
        ),
        migrations.AddField(
            model_name='account',
            name='rest_capital',
            field=models.FloatField(default=0, help_text='资金余额'),
        ),
        migrations.AddField(
            model_name='account',
            name='total_assets',
            field=models.FloatField(default=0, help_text='总资产'),
        ),
    ]
