# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-19 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180319_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moneyhistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('money', models.FloatField(default=0, help_text='资金进出')),
                ('account', models.ForeignKey(help_text='交易账户', on_delete=django.db.models.deletion.CASCADE, to='app.Account')),
            ],
        ),
    ]
