# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-19 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_moneyhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneyhistory',
            name='description',
            field=models.TextField(blank=True, default='', help_text='资金进出说明'),
        ),
    ]
