# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-19 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_moneyhistory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='futuresholdlist',
            name='price',
            field=models.FloatField(default=0, help_text='期货价格'),
        ),
        migrations.AddField(
            model_name='futuresholdlist',
            name='rate',
            field=models.FloatField(default=0, help_text='合约乘数'),
        ),
    ]
