# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-27 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_futureshistory_futureslatestrecord_futuresticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='lastupdate_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='company',
            field=models.ForeignKey(help_text='券商', on_delete=django.db.models.deletion.CASCADE, to='app.Company'),
        ),
    ]
