# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-27 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20171227_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='initial_capital',
            field=models.FloatField(default=0, help_text='初始资金'),
        ),
    ]
