# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-19 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180319_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='futuresholdlist',
            name='price',
        ),
        migrations.AlterField(
            model_name='futuresholdlist',
            name='rate',
            field=models.FloatField(default=0, help_text='保证金率'),
        ),
    ]
