# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-27 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_account_initial_capital'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockhistory',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(default='股票', help_text='账户类型', max_length=50),
        ),
    ]
