# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-30 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_account_market_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='futuresholdlist',
            name='lastprice',
            field=models.FloatField(default=0, help_text='最新价格'),
        ),
        migrations.AddField(
            model_name='futuresholdlist',
            name='volumemultiple',
            field=models.FloatField(default=0, help_text='合约乘数'),
        ),
    ]
