# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-07 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20171227_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='futureshistory',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='futureshistory',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='futureshistory',
            name='earnest_capital',
            field=models.FloatField(default=0, help_text='保证金'),
        ),
        migrations.AddField(
            model_name='futureshistory',
            name='lastupdate_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='futureshistory',
            name='profit_loss',
            field=models.FloatField(default=0, help_text='浮动盈亏'),
        ),
        migrations.AddField(
            model_name='futureshistory',
            name='rest_capital',
            field=models.FloatField(default=0, help_text='资金余额'),
        ),
        migrations.AddField(
            model_name='futureshistory',
            name='total_assets',
            field=models.FloatField(default=0, help_text='总资产'),
        ),
        migrations.AddField(
            model_name='futureslatestrecord',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='futureslatestrecord',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='futureslatestrecord',
            name='earnest_capital',
            field=models.FloatField(default=0, help_text='保证金'),
        ),
        migrations.AddField(
            model_name='futureslatestrecord',
            name='lastupdate_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='futureslatestrecord',
            name='profit_loss',
            field=models.FloatField(default=0, help_text='浮动盈亏'),
        ),
        migrations.AddField(
            model_name='futureslatestrecord',
            name='rest_capital',
            field=models.FloatField(default=0, help_text='资金余额'),
        ),
        migrations.AddField(
            model_name='futureslatestrecord',
            name='total_assets',
            field=models.FloatField(default=0, help_text='总资产'),
        ),
    ]
