# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-12 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20180307_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuturesHoldList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='合约代码', max_length=30)),
                ('number', models.FloatField(default=0, help_text='持仓数量')),
                ('useMargin', models.FloatField(default=0, help_text='占用保证金')),
                ('cost', models.FloatField(default=0, help_text='盈亏成本价')),
                ('direction', models.FloatField(default=0, help_text='交易方向')),
                ('profit_loss', models.FloatField(default=0, help_text='浮动盈亏')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('lastupdate_time', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(help_text='交易账户', on_delete=django.db.models.deletion.CASCADE, to='app.Account')),
            ],
        ),
        migrations.RemoveField(
            model_name='futureslatestrecord',
            name='account',
        ),
        migrations.RemoveField(
            model_name='futuresticket',
            name='account',
        ),
        migrations.RemoveField(
            model_name='stocklatestrecord',
            name='account',
        ),
        migrations.DeleteModel(
            name='FuturesLatestRecord',
        ),
        migrations.DeleteModel(
            name='FuturesTicket',
        ),
        migrations.DeleteModel(
            name='StockLatestRecord',
        ),
    ]
