# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-04 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_account_starttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='starttime',
            field=models.DateField(),
        ),
    ]
